version: '3'

services:
    workspace:
        image: composer:latest
        build:
            context: ./docker
            dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www/html
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - NODE_ENV=production
        links:
            - redis
        working_dir: /var/www/html
        command: tail -f /dev/null

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: exchange_rate
            POSTGRES_USER: default
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:latest
        command: redis-server
        volumes:
            - ./docker/redis:/var/lib/redis
        ports:
            - "6379:6379"
        networks:
            - redis-network

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php

    php:
        image: php:8.2-fpm
        build:
            context: ./docker
            dockerfile: ./Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - NODE_ENV=production
        volumes:
            - ./:/var/www/html
        links:
            - redis
        working_dir: /var/www/html
        depends_on:
            - postgres
            - redis

volumes:
    redis:
    postgres:

networks:
    redis-network:
        driver: bridge
